replicaCount: 1

image:
  repository: deepaktyagi83/go-web-app
  pullPolicy: IfNotPresent
  # CI should update this string to the image tag (use quotes)
  tag: "v1"

ingress:
  enabled: true
  # host used in the chart default â€“ keep in sync with ingress.host if you change
  hosts:
    - host: go-web-app.local
      paths:
        - path: /
          pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
